dbt_financial:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: 02092001
      dbname: financial_data
      schema: financial_raw

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: dbt
      pass: dbt
      dbname: financial_data
      schema: financial_raw

  target: dev
